name: GitCraft
version: '${project.version}'
main: transfem.order.gitcraft.GitCraft
api-version: '1.20'
commands:
  gitcraft:
    description: "GitCraft Command"
    usage: "/<command> [arguments]"
    aliases: []
    permission: gitcraft.command
    permission-message: "You do not have the proper permissions"
permissions:
  gitcraft.view:
    description: "Allows viewing commit worlds"
    default: true
  gitcraft.return:
    description: "Allows returning to the return location"
    default: true
  gitcraft.config:
    description: "Allows configuring Gitcraft settings"
    default: op
  gitcraft.checkout:
    description: "Allows checking out the current world to a new commit world"
    default: op
  gitcraft.commit:
    description: "Allows managing commits"
    default: op
  gitcraft.approve:
    description: "Allows approving commits"
    default: op
  gitcraft.reject:
    description: "Allows rejecting commits"
    default: op

