name: GitCraft
version: '${project.version}'
main: transfem.order.gitcraft.GitCraft
api-version: '1.20'
commands:
  gitcraft:
    description: "GitCraft Command"
    usage: "/<command> [arguments]"
    aliases: []
    permission: gitcraft.command
    permission-message: "You do not have the proper permissions"
permissions:
  gitcraft.command:
    description: "Allows the player to use the gitcraft command"
    default: op
  gitcraft.commit:
    description: "Allows the player to use the commit commands"
    default: op
  gitcraft.commit.manage:
    description: "Allows the player to manage the commits"
    default: op
  gitcraft.manage:
    description: "Allows the player to manage the plugin"
    default: op
